@startuml

class Client

class Context {
-currentState:State
}

interface State {
+doAction(context:Context)
}

class PlayState {
+doAction(context:Context)
}

class PauseState {
+doAction(context:Context)
}

class StopState {
+doAction(context:Context)
}

Context o--> State
State <|-- PlayState
State <|-- PauseState
State <|-- StopState
Client --> Context

@enduml