version: '3.7'
services:
  db:
    container_name: gitops-db
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./../postgres-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
  backend:
    container_name: gitops-server
    build: .
    ports:
      - "8081:8081"
    networks:
      - spring-postgres
    depends_on:
      - db
volumes:
  postgres-data:
networks:
  spring-postgres: